version: 2

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run: apk add make curl
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: debug
          command: 'echo "DOCKER_USERNAME: $DOCKER_USERNAME"'
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run: docker version
      - run: make