version: 2.1

orbs:
  docker-buildx: foodles/docker-buildx@0.0.1

jobs:
  build:
    docker:
      - image: docker:19.03.8
    steps:
      - checkout
      - run: apk add make curl bash git
      - setup_remote_docker:
          version: 18.09.3 # Max supported version was found on https://circleci.com/docs/2.0/building-docker-images/
      - run:
          name: debug env variables
          command: 'echo "DOCKER_USERNAME: $DOCKER_USERNAME"'
      - run:
          name: debug os
          command: 'cat /etc/*release'
      - run:
          name: debug kernel
          command: 'uname -a'
      - run:
          name: debug docker version
          command: 'docker version'
      - run:
          name: debug make version
          command: 'make --version'
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: make build-and-tests
